name: Test project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 1. Install necessary system dependencies for Unity in headless mode
      - name: Install Unity dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-0 libnss3 libxss1 libglib2.0-0 libpulse0 xvfb

      # 2. Clean up the Library folder to prevent cache corruption
      - name: Clean Library folder
        run: rm -rf Library/

      # 3. Cache the Library folder (optional, if you use caching)
      - name: Cache Library folder
        uses: actions/cache@v4
        with:
          path: ./Library
          key: Library-${{ runner.os }}-${{ hashFiles('**/ProjectSettings/ProjectVersion.txt') }}
          restore-keys: |
            Library-

      # 4. Run Unity in headless mode using xvfb
      - name: Run Unity tests
        run: |
          xvfb-run --auto-servernum --server-args='-screen 0 1024x768x24' \
          unity-editor -batchmode -nographics -projectPath . -runTests -testPlatform PlayMode -logfile -

      # 5. Upload test results (if any)
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: TestResults
